# Curve Fitting - bs grewal 24

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as ss
import statistics as st

In [56]:
np.set_printoptions(suppress=False)

### Method of Least Square

In [111]:
# x = np.array([0,1,2])
x = np.arange(5)
y = np.array([1,1.8,1.3,2.5,7.3])

In [84]:
y = np.log10(y)

In [69]:
x = np.power(np.e, x)

In [85]:
x, y

(array([2, 3, 4, 5, 6]),
 array([2.15836249, 2.23754374, 2.31680875, 2.39585038, 2.47494434]))

In [114]:
np.sum(x*x)

30

In [35]:
np.sum(x**4)

548.1875

In [95]:
10**(2.0001138089085906) 

100.02620890357021

In [31]:
0.004170389021173743/np.log10(np.e)

0.00960267559214069

In [109]:
# Linear equation least square
# a1x + b1y = c1
# a2x + b2y = c2

a1, b1, c1 = 10,50,80 # x.size, np.sum(x), np.sum(y)
a2, b2, c2 = 50,750, 1030 #np.sum(x), np.sum(x**2), np.sum(x*y)

a, b = (c1*b2 - c2*b1) / (a1*b2 - a2*b1), (c2*a1 - c1*a2) / (a1*b2 - a2*b1)
print(a, b)

1.7 1.26


In [182]:
# Quadratic quation least square

a = np.array([
        [x.size, np.sum(x), np.sum(x**2)],
        [np.sum(x), np.sum(x**2), np.sum(x**3)],
        [np.sum(x**2), np.sum(x**3), np.sum(x**4)]
    ])
b = np.array([np.sum(y), np.sum(x*y),np.sum(x*x*y)])

np.linalg.solve(a,b)

array([-0.46      ,  1.84285714,  0.44285714])

In [93]:
book = 99.86*1.2**(x)

In [100]:
my = 100.026*1.199**(x)

In [97]:
y

array([144. , 172.8, 207.4, 248.8, 298.5])

In [25]:
# Linear quation least square

a = np.array([
        [x.size, np.sum(x)],
        [np.sum(x), np.sum(x**2)]
    ])
b = np.array([np.sum(y), np.sum(x*y)])

np.linalg.solve(a,b)

array([0.18393168, 0.00960268])

In [101]:
np.sqrt(np.sum((y-my)**2) / y.size)

0.8070581599326697

In [99]:
np.sqrt(np.sum((y-book)**2) / y.size)

0.28653919910301673

In [45]:
np.e**0.18

1.1972173631218102

### Method of Group Averages

In [185]:
x = np.array([5,10,20,30,35,40])
y = np.array([10,14,25,40,50,62])

# x = np.arange(5, 41, 5)

In [186]:
x = np.delete(x, 1)
y = np.delete(y, 1)

m, n = 2.5, 17.8
X = x + m
Y = (y - n) / (x - m)

In [179]:
x, y

(array([ 5, 10, 20, 30, 35, 40]), array([10, 14, 25, 40, 50, 62]))

In [152]:
np.mean([81.1,  87.2,  95.5, 102.2,
        108.4])

94.88

In [182]:
np.mean([3.68887945, 3.91202301,
       4.12713439])

3.9093456166666667

In [183]:
# Quadratic equation group average
# y1_ = a1 + b1x1_
# y2_ = a2 + b2x2_

a1, b1, c1 = 1, 11.6, 2.720
a2, b2, c2 = 1, 35, 3.909

a, b = (c1*b2 - c2*b1) / (a1*b2 - a2*b1), (c2*a1 - c1*a2) / (a1*b2 - a2*b1)
print(a, b)

2.130581196581197 0.0508119658119658


In [172]:
n - a*m - b*m*m

15.447359154929577

In [133]:
x = np.log10(x)

In [180]:
np.log(y)

array([2.30258509, 2.63905733, 3.21887582, 3.68887945, 3.91202301,
       4.12713439])

In [135]:
x, y

(array([1.30103   , 1.60205999, 1.77815125, 1.90308999, 2.        ]),
 array([0.12483015, 0.72697158, 1.01422643, 1.32905193, 1.509646  ]))

In [142]:
10**(-2.414090909090909)

0.003853976754995886

In [188]:
my = 1.459*np.e**(0.062*x)

np.sqrt(np.sum((y-my)**2) / y.size)

30.89720953996037

In [184]:
np.e**(2.130581196581197 )

8.419758924764226

### Method of Moments

In [2]:
from scipy import integrate

In [92]:
x = np.arange(1,5)
y = np.array([0.30,0.64,1.32,5.40])

h = 1

In [194]:
ss.moment(y, 2)

14.5

In [193]:
np.var(y)

14.5

In [93]:
# Observed Moments

for i in range(3):
    globals()[f'em{i+1}'] = (1 * np.sum(y*x**i))

em1, em2, em3

(7.66, 27.14, 101.14)

In [94]:
# Calculated moments

for p in range(1,6):
    globals()[f'mu{p}'] = ((a**p - b**p)/p)

mu1, mu2, mu3, mu4, mu5

(4.0, 10.0, 30.333333333333332, 102.5, 369.05)

In [95]:
a, b = x[-1] + h/2, x[0] - h/2
print(a,b)

4.5 0.5


In [79]:
# Linear equation method of moment
# a1x + b1y = c1
# a2x + b2y = c2
a1, b1, c1 = mu1, mu2, em1
a2, b2, c2 = mu2, mu3, em2

a, b = (c1*b2 - c2*b1) / (a1*b2 - a2*b1), (c2*a1 - c1*a2) / (a1*b2 - a2*b1)
print(a, b)

0.5919947679790719 0.2616010464041855


In [96]:
# Quadratic quation method of moment

m = np.array([
        [mu1, mu2, mu3],
        [mu2, mu3, mu4],
        [mu3, mu4, mu5]
    ])
n = np.array([em1, em2, em3])

np.linalg.solve(m,n)

array([ 0.85032715, -1.22794922,  0.54521484])

In [99]:
my = 0.485+0.397*x+0.124*x*x

np.sqrt(np.sum((y-my)**2) / y.size)

1.1996972534768928

In [77]:
np.sum(x*y)

116.8

In [55]:
def function(x,a,b):
    return a*x + b

integrate.quad(func=lambda x: x, a=4.5, b=0.5)

(-10.0, 1.1102230246251565e-13)

In [105]:
# Final method

x = np.arange(1,10,2)
y = np.array([1.5,2.8,4,4.7,6])
h = 2

a, b = x[-1] + h/2, x[0] - h/2

# Observed Moments
for i in range(3):
    globals()[f'em{i+1}'] = (1 * np.sum(y*x**i))

# Calculated moments
for p in range(1,6):
    globals()[f'mu{p}'] = ((a**p - b**p)/p)

# Linear equation method of moment
a1, b1, c1 = mu1, mu2, em1
a2, b2, c2 = mu2, mu3, em2

a, b = (c1*b2 - c2*b1) / (a1*b2 - a2*b1), (c2*a1 - c1*a2) / (a1*b2 - a2*b1)
print(a, b)

# Quadratic quation method of moment
m = np.array([
        [mu1, mu2, mu3],
        [mu2, mu3, mu4],
        [mu3, mu4, mu5]
    ])
n = np.array([em1, em2, em3])

a, b, c = np.linalg.solve(m,n)
print(a,b,c)

# SEE
my = a+b*x #+c*x*x
print(np.sqrt(np.sum((y-my)**2) / y.size))

0.5919999999999999 0.2616000000000001
0.3419999999999978 0.4116000000000013 -0.01500000000000013
1.4567650737164128
